Task: OCT
TrainingFraction:
- 0.95
alphavalue: 0.7
batch_size: 8
bodyparts:
- l_1_0
- l_1_1
- l_1_2
- l_1_3
- l_1_4
- l_1_5
- l_1_6
- l_1_7
- l_1_8
- l_1_9
- l_1_10
- l_1_11
- l_1_12
- l_1_13
- l_1_14
- l_1_15
- l_1_16
- l_1_17
- l_1_18
- l_1_19
- l_1_20
- l_1_21
- l_1_22
- l_1_23
- l_1_24
- l_1_25
- l_1_26
- l_1_27
- l_1_28
- l_1_29
- l_2_0
- l_2_1
- l_2_2
- l_2_3
- l_2_4
- l_2_5
- l_2_6
- l_2_7
- l_2_8
- l_2_9
- l_2_10
- l_2_11
- l_2_12
- l_2_13
- l_2_14
- l_2_15
- l_2_16
- l_2_17
- l_2_18
- l_2_19
- l_2_20
- l_2_21
- l_2_22
- l_2_23
- l_2_24
- l_2_25
- l_2_26
- l_2_27
- l_2_28
- l_2_29
- l_3_0
- l_3_1
- l_3_2
- l_3_3
- l_3_4
- l_3_5
- l_3_6
- l_3_7
- l_3_8
- l_3_9
- l_3_10
- l_3_11
- l_3_12
- l_3_13
- l_3_14
- l_3_15
- l_3_16
- l_3_17
- l_3_18
- l_3_19
- l_3_20
- l_3_21
- l_3_22
- l_3_23
- l_3_24
- l_3_25
- l_3_26
- l_3_27
- l_3_28
- l_3_29
- l_4_0
- l_4_1
- l_4_2
- l_4_3
- l_4_4
- l_4_5
- l_4_6
- l_4_7
- l_4_8
- l_4_9
- l_4_10
- l_4_11
- l_4_12
- l_4_13
- l_4_14
- l_4_15
- l_4_16
- l_4_17
- l_4_18
- l_4_19
- l_4_20
- l_4_21
- l_4_22
- l_4_23
- l_4_24
- l_4_25
- l_4_26
- l_4_27
- l_4_28
- l_4_29
- l_5_0
- l_5_1
- l_5_2
- l_5_3
- l_5_4
- l_5_5
- l_5_6
- l_5_7
- l_5_8
- l_5_9
- l_5_10
- l_5_11
- l_5_12
- l_5_13
- l_5_14
- l_5_15
- l_5_16
- l_5_17
- l_5_18
- l_5_19
- l_5_20
- l_5_21
- l_5_22
- l_5_23
- l_5_24
- l_5_25
- l_5_26
- l_5_27
- l_5_28
- l_5_29
colormap: plasma
corner2move2:
- 50
- 50
croppedtraining: false
cropping: false
date: Nov3
default_augmenter: default
default_net_type: resnet_50
dotsize: 12
iteration: 0
move2corner: true
multianimalproject: false
numframes2pick: 20
pcutoff: 0.6
project_path: D:\Science\oct\code/network
scorer: ARVIN
skeleton:
- l_3_22
skeleton_color: black
snapshotindex: -1
start: 0
stop: 1
x1: 0
x2: 640
y1: 277
y2: 624
